const { Client, GatewayIntentBits, Partials, ActivityType, EmbedBuilder, PermissionsBitField } = require('discord.js');

const client = new Client({
  intents: [
      GatewayIntentBits.Guilds,
          GatewayIntentBits.GuildMembers,
              GatewayIntentBits.GuildMessages,
                  GatewayIntentBits.MessageContent,
                      GatewayIntentBits.GuildPresences,
                          GatewayIntentBits.GuildVoiceStates,
                            ],
                              partials: [Partials.Channel, Partials.Message, Partials.GuildMember],
                              });

                              const PREFIX = '!';
                              const GUILD_ID = '1487503515512475792';

                              // ── Ready ──────────────────────────────────────────────────────────────────
                              client.once('ready', () => {
                                console.log(`Online as ${client.user.tag}`);
                                  client.user.setPresence({
                                      activities: [{ name: 'RazorReaper | rr.sellhub.cx', type: ActivityType.Watching }],
                                          status: 'online',
                                            });
                                            });

                                            // ── Welcome new members ────────────────────────────────────────────────────
                                            client.on('guildMemberAdd', async (member) => {
                                              const channel = member.guild.channels.cache.find(c => c.name.includes('welcome'));
                                                if (!channel) return;
                                                  const embed = new EmbedBuilder()
                                                      .setColor(0x00ffff)
                                                          .setTitle('⚡ Welcome to RazorReaper!')
                                                              .setDescription(`Hey ${member}, glad to have you here.\nRead the rules and enjoy your stay.`)
                                                                  .setThumbnail(member.user.displayAvatarURL({ dynamic: true }))
                                                                      .setFooter({ text: 'RazorReaper Bot', iconURL: client.user.displayAvatarURL() })
                                                                          .setTimestamp();
                                                                            channel.send({ embeds: [embed] });
                                                                            });

                                                                            // ── Commands ───────────────────────────────────────────────────────────────
                                                                            client.on('messageCreate', async (message) => {
                                                                              if (message.author.bot || !message.content.startsWith(PREFIX)) return;

                                                                                const args = message.content.slice(PREFIX.length).trim().split(/ +/);
                                                                                  const command = args.shift().toLowerCase();

                                                                                    // !ping
                                                                                      if (command === 'ping') {
                                                                                          const embed = new EmbedBuilder()
                                                                                                .setColor(0x00ffff)
                                                                                                      .setDescription(`⚡ Pong! \`${client.ws.ping}ms\``);
                                                                                                          return message.reply({ embeds: [embed] });
                                                                                                            }
                                                                                                            
                                                                                                              // !info
                                                                                                                if (command === 'info') {
                                                                                                                    const guild = message.guild;
                                                                                                                        const embed = new EmbedBuilder()
                                                                                                                              .setColor(0x9b59b6)
                                                                                                                                    .setTitle('⚙️ RazorReaper Server Info')
                                                                                                                                          .addFields(
                                                                                                                                                  { name: 'Members', value: `${guild.memberCount}`, inline: true },
                                                                                                                                                          { name: 'Created', value: `<t:${Math.floor(guild.createdTimestamp / 1000)}:R>`, inline: true },
                                                                                                                                                                  { name: 'Owner', value: `<@${guild.ownerId}>`, inline: true },
                                                                                                                                                                        )
                                                                                                                                                                              .setThumbnail(guild.iconURL({ dynamic: true }))
                                                                                                                                                                                    .setTimestamp();
                                                                                                                                                                                        return message.reply({ embeds: [embed] });
                                                                                                                                                                                          }
                                                                                                                                                                                          
                                                                                                                                                                                            // !userinfo [@user]
                                                                                                                                                                                              if (command === 'userinfo') {
                                                                                                                                                                                                  const target = message.mentions.members.first() || message.member;
                                                                                                                                                                                                      const embed = new EmbedBuilder()
                                                                                                                                                                                                            .setColor(0x00ffff)
                                                                                                                                                                                                                  .setTitle(`👤 ${target.user.tag}`)
                                                                                                                                                                                                                        .addFields(
                                                                                                                                                                                                                                { name: 'Joined Server', value: `<t:${Math.floor(target.joinedTimestamp / 1000)}:R>`, inline: true },
                                                                                                                                                                                                                                        { name: 'Account Created', value: `<t:${Math.floor(target.user.createdTimestamp / 1000)}:R>`, inline: true },
                                                                                                                                                                                                                                                { name: 'Top Role', value: `${target.roles.highest}`, inline: true },
                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                            .setThumbnail(target.user.displayAvatarURL({ dynamic: true }))
                                                                                                                                                                                                                                                                  .setTimestamp();
                                                                                                                                                                                                                                                                      return message.reply({ embeds: [embed] });
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                          // !purge [amount] — staff only
                                                                                                                                                                                                                                                                            if (command === 'purge') {
                                                                                                                                                                                                                                                                                if (!message.member.permissions.has(PermissionsBitField.Flags.ManageMessages))
                                                                                                                                                                                                                                                                                      return message.reply('❌ No permission.');
                                                                                                                                                                                                                                                                                          const amount = parseInt(args[0]);
                                                                                                                                                                                                                                                                                              if (isNaN(amount) || amount < 1 || amount > 100)
                                                                                                                                                                                                                                                                                                    return message.reply('❌ Provide a number between 1-100.');
                                                                                                                                                                                                                                                                                                        await message.channel.bulkDelete(amount + 1, true).catch(() => {});
                                                                                                                                                                                                                                                                                                            const msg = await message.channel.send({ embeds: [new EmbedBuilder().setColor(0x00ffff).setDescription(`🗑️ Deleted ${amount} messages.`)] });
                                                                                                                                                                                                                                                                                                                setTimeout(() => msg.delete().catch(() => {}), 3000);
                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                    // !kick [@user] [reason]
                                                                                                                                                                                                                                                                                                                      if (command === 'kick') {
                                                                                                                                                                                                                                                                                                                          if (!message.member.permissions.has(PermissionsBitField.Flags.KickMembers))
                                                                                                                                                                                                                                                                                                                                return message.reply('❌ No permission.');
                                                                                                                                                                                                                                                                                                                                    const target = message.mentions.members.first();
                                                                                                                                                                                                                                                                                                                                        if (!target) return message.reply('❌ Mention a user.');
                                                                                                                                                                                                                                                                                                                                            const reason = args.slice(1).join(' ') || 'No reason provided';
                                                                                                                                                                                                                                                                                                                                                await target.kick(reason);
                                                                                                                                                                                                                                                                                                                                                    message.reply({ embeds: [new EmbedBuilder().setColor(0xff0000).setDescription(`✅ Kicked **${target.user.tag}** — ${reason}`)] });
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                        // !ban [@user] [reason]
                                                                                                                                                                                                                                                                                                                                                          if (command === 'ban') {
                                                                                                                                                                                                                                                                                                                                                              if (!message.member.permissions.has(PermissionsBitField.Flags.BanMembers))
                                                                                                                                                                                                                                                                                                                                                                    return message.reply('❌ No permission.');
                                                                                                                                                                                                                                                                                                                                                                        const target = message.mentions.members.first();
                                                                                                                                                                                                                                                                                                                                                                            if (!target) return message.reply('❌ Mention a user.');
                                                                                                                                                                                                                                                                                                                                                                                const reason = args.slice(1).join(' ') || 'No reason provided';
                                                                                                                                                                                                                                                                                                                                                                                    await target.ban({ reason });
                                                                                                                                                                                                                                                                                                                                                                                        message.reply({ embeds: [new EmbedBuilder().setColor(0xff0000).setDescription(`✅ Banned **${target.user.tag}** — ${reason}`)] });
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                            // !help
                                                                                                                                                                                                                                                                                                                                                                                              if (command === 'help') {
                                                                                                                                                                                                                                                                                                                                                                                                  const embed = new EmbedBuilder()
                                                                                                                                                                                                                                                                                                                                                                                                        .setColor(0x9b59b6)
                                                                                                                                                                                                                                                                                                                                                                                                              .setTitle('⚡ RazorReaper Bot — Commands')
                                                                                                                                                                                                                                                                                                                                                                                                                    .addFields(
                                                                                                                                                                                                                                                                                                                                                                                                                            { name: '`!ping`', value: 'Check bot latency', inline: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                    { name: '`!info`', value: 'Server information', inline: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                            { name: '`!userinfo [@user]`', value: 'User information', inline: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                    { name: '`!purge [1-100]`', value: 'Bulk delete messages', inline: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                            { name: '`!kick [@user]`', value: 'Kick a member', inline: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { name: '`!ban [@user]`', value: 'Ban a member', inline: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .setFooter({ text: 'RazorReaper Bot | rr.sellhub.cx' })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .setTimestamp();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return message.reply({ embeds: [embed] });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            client.login(process.env.TOKEN);
