name: Deploy to JustRunMy.App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to JustRunMy.App
        run: |
          git remote add deploy ${{ secrets.JUSTRUNMYAPP_GIT_URL }}
          git push -f deploy HEAD:deploy
